<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" Exclude="bin\**;obj\**;CodeCakeBuilder\**;packages\**;@(EmbeddedResource)" />
    <None Remove="Res\**\*.sql;Res\**\*.tql" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="CK.Globalization" Version="5.0.1--ci.4" />
    <PackageReference Include="CK.SqlServer.Dapper" Version="15.0.1--ci.4" />
    <PackageReference Include="CK.SqlServer.Setup.Model" Version="33.0.1--ci.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CK.IO.Globalization\CK.IO.Globalization.csproj" />
  </ItemGroup>

</Project>
