<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
     <PackageReference Include="CK.Cris.Engine" Version="0.43.0" />
    <PackageReference Include="CK.Poco.Exc.Json.Engine" Version="33.0.0" />
    <PackageReference Include="CK.TypeScript.Engine" Version="0.31.1" />

    <PackageReference Include="CK.SqlServer.Setup.Engine" Version="33.0.0" />
    <PackageReference Include="CK.DB.Tests.NUnit" Version="33.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" PrivateAssets="all" /> 
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CK.DB.Globalization\CK.DB.Globalization.csproj" />
  </ItemGroup>

</Project>
